UserAgentHeaderProvider unit test case added
GoogleCloudDataproc/flink-bigquery-connector pull request #26
Opened 2022-05-02 14:17 UTC by Sridhar-Durgam2022

2022-05-03 00:32 UTC, davidrabinowitz commented
/gcbrun

2022-05-03 00:39 UTC, davidrabinowitz requested changes
what about testing the `UserAgentProvider` ?

2022-05-03 00:39 UTC, davidrabinowitz commented on src/test/java/com/google/cloud/flink/bigquery/UserAgentHeaderProviderTest.java
> +    assertThat(resultMap instanceof Map).isTrue();
redundant test

2022-05-03 00:39 UTC, davidrabinowitz commented on src/test/java/com/google/cloud/flink/bigquery/UserAgentHeaderProviderTest.java
> +    assertThat(userAgent instanceof String).isTrue();
redundant test

2022-05-05 11:46 UTC, Sridhar-Durgam2022 commented on src/test/java/com/google/cloud/flink/bigquery/UserAgentHeaderProviderTest.java
> +    assertThat(resultMap instanceof Map).isTrue();
Removed

2022-05-05 11:46 UTC, Sridhar-Durgam2022 commented on src/test/java/com/google/cloud/flink/bigquery/UserAgentHeaderProviderTest.java
> +    assertThat(userAgent instanceof String).isTrue();
removed

2022-05-17 22:49 UTC, davidrabinowitz approved these changes

2022-05-17 22:49 UTC, merged