Adds example and distribution modules
GoogleCloudDataproc/flink-bigquery-connector pull request #47
Opened 2023-06-29 18:17 UTC by prodriguezdefino

Also fixes a NPE when the underlying table in BQ gets expired, now returns a proper exception.

2023-07-11 22:31 UTC, prodriguezdefino commented on flink-connector-bigquery-examples/src/main/java/org/apache/flink/examples/gcp/bigquery/BigQueryExample.java
> + * 19:00:00\u0027"}.
@sonatype-lift ignore

2023-08-03 23:02 UTC, prodriguezdefino commented
/gcbrun

2023-08-08 23:49 UTC, prodriguezdefino commented
/gcbrun

2023-08-10 00:54 UTC, prodriguezdefino commented
/gcbrun

2023-11-02 23:23 UTC, prodriguezdefino commented
/gcbrun

2023-11-03 18:34 UTC, prodriguezdefino commented
/gcbrun

2023-11-24 06:52 UTC, jayehwhyehentee commented
/gcbrun

2023-11-24 08:06 UTC, jayehwhyehentee commented
/gcbrun

2023-11-24 08:24 UTC, jayadeep-jayaraman commented on flink-connector-bigquery-examples/src/main/java/org/apache/flink/examples/gcp/bigquery/BigQueryExample.java
> +        env.enableCheckpointing(60000L);
Can we pass this as a user provided configuration and have this value as a default if user does not pass the value

2023-11-24 08:25 UTC, jayadeep-jayaraman commented on flink-connector-bigquery-examples/src/main/java/org/apache/flink/examples/gcp/bigquery/BigQueryExample.java
> +                .keyBy(t -> t.f0)
let's have meaningful variable names

2023-11-24 08:26 UTC, jayadeep-jayaraman commented on flink-connector-bigquery-examples/src/main/java/org/apache/flink/examples/gcp/bigquery/BigQueryExample.java
> +public class BigQueryExample {
Please add usage guide on how to use this example

2023-11-27 08:34 UTC, jayehwhyehentee commented
/gcbrun

2023-11-27 08:39 UTC, jayehwhyehentee commented on flink-connector-bigquery-examples/src/main/java/org/apache/flink/examples/gcp/bigquery/BigQueryExample.java
> +                .keyBy(t -> t.f0)
Changed `t` to `mappedTuple`.

2023-11-27 12:04 UTC, jayadeep-jayaraman requested changes

2023-11-27 12:04 UTC, jayadeep-jayaraman commented on flink-connector-bigquery-examples/src/main/java/org/apache/flink/examples/gcp/bigquery/BigQueryExample.java
> +        env.enableCheckpointing(60000L);
I meant `60000L` can be passed as a configuration instead of hardcoding. So that users can run this with different checkpoint intervals

2023-11-27 12:45 UTC, jayehwhyehentee commented
/gcbrun

2023-11-27 13:04 UTC, jayadeep-jayaraman approved these changes

2023-11-27 13:05 UTC, merged